version: "2"
services:
    mysql:
        image: mysql:5.7
        container_name: mysqldb
        ports:
            - "4000:3306"
        expose:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: yourrootpassword
    site:
        build: ./
        container_name: myinsead-dev
        volumes:
          - ./app:/var/www/html
        ports:
            - "80:80"
            - "443:443"
        expose:
            - "80"
            - "443"
        depends_on:
            - mysql
        tty: true
        